import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import FilterMenu, { FilterMenuSectionProps } from "@/components/FilterMenu";
import { useContext } from "react";
import FilterSettingsContext, { FilterSettings } from "@/components/FilterMenu/FilterMenuContext";

const inter = Inter({ subsets: ["latin"] });

export const MyFilterSection = (props: FilterMenuSectionProps) => {
  const filterSettings = useContext(FilterSettingsContext);

  const handleClick = () => {
    console.log(filterSettings);
    filterSettings?.setFilterSelection("1", ["1"])
  };

  return (
    <button onClick={() => handleClick()}>klikk mæ</button>
  );
}

export const MyFilterSection2 = (props: FilterMenuSectionProps) => {
  const filterSettings = useContext(FilterSettingsContext);

  return (
    <div>
      {filterSettings?.selectedFilters}
    </div>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className={styles.center}>
          <FilterMenu>
            <MyFilterSection
              filterSectionId="1"
              filterSectionTitle="Filter 1"
            >
            </MyFilterSection>
            <MyFilterSection2
              filterSectionId="2"
              filterSectionTitle="Filter 2"
            >
            </MyFilterSection2>
          </FilterMenu>
        </div >
      </main >
    </>
  );
}
